### ISSUE TITLE
What is vendor_id on users?

### ISSUE THREAD

**Issue by ihassin** [strangerloops/rally_backend#2]
What is vendor_id on users?

**Comment by strangerloops** [comment]
device UDID associated with that user (see user creation on the front end, line ~26 LaunchViewController)

**Comment by ihassin** [comment]
So why not call it that?

**Comment by strangerloops** [comment]
because it's not actually a UDID, it's called the "vendor identifier"

**Comment by ihassin** [comment]
Fair enough lol
